[package]
name = "pasatanda_move_smartcontracts"
edition = "2024"
license = "MIT"
authors = ["PasaTanda Team"]

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
pasatanda_move_smartcontracts = "0x0"
sui = "0x2"
